### ISSUE TITLE
Compilation and building on windows

### ISSUE THREAD

**Issue by darcys22** [darcys22/godbledger#100]
Eventually will want to support running on windows aswell.

- add to continuous integration
- add to releases script

**Comment by davidalpert** [comment]
while working on #103 (PR inbound) I added an `xgo`-based windows build target to the makefile and was able to generate 386 and x64 windows builds. here is a screenshot of godbledger running on a Windows Server 2016 VM:

![image](https://user-images.githubusercontent.com/43332/99622596-1bc95000-29f0-11eb-94c3-81feeb365f66.png)

looks to start up just fine, although the terminal color codes obscure the output.  it may make sense to add some flags or options to configure log output and swap out the color-based log sink for a text-based one when GOOS = windows?

**Comment by darcys22** [comment]
This is awesome, there is already a flag for logfiles that clears the colours using the following:

```
		if logFileName != "" {
			customFormatter.DisableColors = true
			if err := cmd.ConfigurePersistentLogging(logFileName); err != nil {
				log.WithError(err).Error("Failed to configuring logging to disk.")
			}
		}
```

Something similar for windows would possibly work to help their logging

**Comment by davidalpert** [comment]
in #106 `build` and `test` are invoked natively using github actions on:
- `untuntu-latest`
- `macos-latest`
- `windows-latest`

to verify that the app builds and starts on each OS, respectively.

#105 updates the Makefile such that `make` builds native binaries on each OS and `make build-cross` uses `xgo` to build on multiple operating systems including windows.
