### ISSUE TITLE
Support Deployment to Kubernetes

### ISSUE THREAD

**Issue by davidalpert** [darcys22/godbledger#127]
[Kubernetes](https://kubernetes.io/) (often abbreviated as `k8s`) is a common orchestration platform for automating the deployment, scaling, and management of containerized applications.

I recently drafted a set of kubernetes resource specs and a sample `config.toml` file which can take the `godbledger:latest` image built from running `make docker-build` and deploy it locally to the kubernetes cluster hosted in my MacOS [`Docker Desktop`](https://www.docker.com/products/docker-desktop).  While these specs work for a local k8s cluster, they would serve as a useful example of how to deploy godbledger with a mysql backend a corporate or cloud-hosted k8s cluster.

I would like to contribute these resource specs and some related "deploying to kubernetes" docs.

- Where would the YAML and TOML files go? 
- Where should the documentation go?

Locally I have a set of files:
- k8s.00.namespace.yml
- k8s.01.mysql.secrets.yml
- k8s.02.mysql.volume.yml
- k8s.03.mysql.yml
- k8s.04.godbledger.yml
- k8s.config.toml

This sets up:
- a `godbledger` namespace;
- a k8s secret resource with the mysql root password and godbledge username and password;
- a persistent volume and persistent volume claim for the mysql server to user;
- a `mysql` k8s service and deployment;
- a `godbledger` k8s service and deployment;
- a `k8s.config.toml` config file which the local apps can use to talk to the `godbledger` and `mysql` services

**Comment by darcys22** [comment]
I am thinking that either `/utils/kubernetes` or `/build/kubernetes`. We are starting to accumulate a bunch of these environmental config files (ie i made a `/utils/deb` folder for similar config files in #126) and think that more will come so probably good to get a formal place decided for them all

**Comment by davidalpert** [comment]
merged to `dev`
