### ISSUE TITLE
Integrate Message broker for events monitoring

### ISSUE THREAD

**Issue by mingsterism** [darcys22/godbledger#165]
A message broker like NATS or Kafka will allow any other system to listen to events happening on GoDbLedger. 
This allow for other systems to integrate cleanly with the system without having any tight coupling. 
Possible **Event Schema** topics
1) transaction.created
2) transaction.deleted

The event schema needs to be designed well before Keen to hear thoughts on what the topics could be

Other systems can subscribe to specific topics like `transaction.created` or use wildcards like `transaction.*` to listen to all the transactions.

**Comment by darcys22** [comment]
I've also heard of accounting systems using a messaging system like this to drive the double entry transactions! For example the RPC message comes through to the log system, then the system picks up the events to create the transactions.

its probably an area I don't have a lot of experience in but definitely interested in exploring!

**Comment by mingsterism** [comment]
got it. which file / folder would be a good place to start to integrate the message broker within the system?

**Comment by darcys22** [comment]
Likely a subfolder under the godbledger executable folder.

https://github.com/darcys22/godbledger/tree/master/godbledger

if you look at how node is implemented it spins up via a service interface that can be started and stopped. Something similar to it so that the messaging can be run in its own service

**Comment by mingsterism** [comment]
noted. thanks for the clarification
