### ISSUE TITLE
Automatic tax calculation

### ISSUE THREAD

**Issue by mingsterism** [darcys22/godbledger#168]
Can GODbLedger assist companies with automtically calculating their tax. 
Is this within the features of the system. If yes, what needs to be done?

**Comment by darcys22** [comment]
Yes! Very much so. however its a long term goal that needs a fair bit of infrastructure first.

Implementation would likely be as a submodule of godbledger-web (or standalone product) that take a general ledger and maps to a list of tax return fields which could then be lodged via an api or simply outputted to a pdf for manual entry.

**Comment by mingsterism** [comment]
got it. thanks for the clarification
