### ISSUE TITLE
Rename Brief in the transactions table to description

### ISSUE THREAD

**Issue by darcys22** [darcys22/godbledger#171]
to keep things consistent

**Comment by 00Masato** [comment]
@darcys22 
Hi, Can I give it a try?

**Comment by darcys22** [comment]
Hi @00Masato 

You are very welcome to give it a go!

Key places to look are in the database folders.

https://github.com/darcys22/godbledger/blob/master/godbledger/db/mysqldb/mysqldb.go

That file for example is where the MySQL database is initialised and sqlite has a pretty much identical file under db/sqlite3db. They both have an InitDB() function which builds the initial database. In there you will be able to see where the Transaction table is built.

but you should just be able to ctrl-f for brief in the 4 files under godbledger/db to find all the references to that column.

Hopefully that makes some sense, feel free to ask any questions and ill be happy to help :)

**Comment by 00Masato** [comment]
@darcys22 
Raised PR.
Please review it!

**Comment by darcys22** [comment]
Thank you!
