### ISSUE TITLE
Exporting Profit and Loss and other reports as excel (.xlxs)

### ISSUE THREAD

**Issue by ghost** [darcys22/godbledger#64]
To actually view your financial information we should query the database directly in Excel(.xlxs) format is may be good option with other Formats that you included.

**Comment by darcys22** [comment]
Thanks for the message!

Could you clarify if you mean implementing a database backend in excel? Or simply exporting the `ledger_cli` reports as .xlxs files (CSV already exists there).

Actually both are interesting ideas. I would note however that excel itself already has the ability to open both [MySQL](https://www.mysql.com/why-mysql/windows/excel/) and [SQLite](https://www.devart.com/odbc/sqlite/docs/excel.htm) as datasources.

**Comment by paraardh** [comment]
This idea is for exporting Profit&Loss summary into EXCEL because you
mentioned it to make a worldwide use of it. So, for that Exporting data
into EXCEL is best for south-asia regions because they generally use EXCEL
rather than CSV format.

Regards,
Manish S. (@paraardh)

**Comment by darcys22** [comment]
Awesome, thanks for clarifying. Its easy enough to implement. Thinking possibly more appropriate to add it to the GUI client that is being created rather than in the CLI.

But if there is enough interest it shouldn't be too hard to do in both

**Comment by paraardh** [comment]
If this is the case than you can leave it on GUI.

**Comment by darcys22** [comment]
Have addressed this in godbledger-web in the latest commit. GoDBLedger web is still in alpha but the reports pages will have export to PDF/Excel etc built in
