### ISSUE TITLE
[Feature Request] Database Fields Documentation

### ISSUE THREAD

**Issue by vzool** [darcys22/godbledger#77]
Hi, I'm a developer and I like the project idea. But, I have some experience about Accounting. If there will be a documentation for every single field which explains (**Data Type, Length, Key Restrictions & Relationships**). So, all contributors will be in the same level of knowledge about the whole project at general.
Thanks

**Comment by darcys22** [comment]
Yes!

The documentation right now is very light and I 100% need to get the database schema down into the wiki.

Ill have look into it and see if i can draft up an initial page this week.

In the interim the schema is heavily based upon GNUCash and their design here:

https://wiki.gnucash.org/wiki/SQL

Was pretty much my goto reference when I was building GoDBLedger. The core tables for accounts, transactions and splits are essentially the same idea.

**Comment by darcys22** [comment]
So I have drafted up this page on the wiki:
https://github.com/darcys22/godbledger/wiki/SQL-Schema-and-Database-Information

It has room for improvement but definitely a start.

If you want to discuss your ideas send us a message on discord:
https://discord.gg/xHFufYC

**Comment by vzool** [comment]
Much better, this is simpler than [GnuCash SQL](https://wiki.gnucash.org/wiki/SQL).
